### ISSUE TITLE
Multiple @material-ui/styles instances

### ISSUE THREAD

**Issue by saschb2b** [unicef/material-ui-currency-textfield#10]
I have an existing project with `@material-ui/core` version 4.4.2 which uses `@material-ui/styles@4.4.1`

This component has mui as a dependency rather than a peer dep. Which causes a duplicate instance of the styles package

```
It looks like there are several instances of `@material-ui/styles` initialized in this application.
This may cause theme propagation issues, broken class names, specificity issues, and makes your application bigger without a good reason.

See https://material-ui.com/r/styles-instance-warning for more info.
```

![image](https://user-images.githubusercontent.com/2778161/70985937-4793d580-20bd-11ea-92d6-6a5854b405c0.png)

You should consider making it a peer dep

**Comment by merlos** [comment]
Thanks @saschb2b 
We'll take a look.
