### ISSUE TITLE
Set the value through the state

### ISSUE THREAD

**Issue by gpigatto** [unicef/material-ui-currency-textfield#11]
Doing something like this:
`resetValue = () => {
        this.setState({
          value: 0,
        });
      };`
will not work as it work in any other text field.

**Comment by raduGaspar** [comment]
This should be fixed as it can't be used as a controlled component with the current implementation.

**Comment by sureshsevarthi** [comment]
Hey @gpigatto, we will look in to it.

**Comment by PhilSchwerttraeger** [comment]
Got the same issue. This is a very serious problem.

**Comment by sureshsevarthi** [comment]
@gpigatto @raduGaspar @PhilSchwerttraeger Fixed the issue, will be available in version 0.8.6

**Comment by alfondotnet** [comment]
@sureshsevarthi This fix I think introduced a regression as seen in: https://github.com/unicef/material-ui-currency-textfield/issues/17

**Comment by dborstelmann** [comment]
Yes this is also broken for me, setValue(undefined) does not work to clear the input
