### ISSUE TITLE
Could not find a declaration file for module '@unicef/material-ui-currency-textfield'

### ISSUE THREAD

**Issue by Klekito** [unicef/material-ui-currency-textfield#12]
Hi,

After installing the module I cannot import it because of this message.
I've tried installing '@types/unicef__material-ui-currency-textfield' too but it gives me 404.

`"@unicef/material-ui-currency-textfield": "^0.8.4"`
`"react": "^16.4.2"`

> Could not find a declaration file for module '@unicef/material-ui-currency-textfield'. '/home/nilton/Projects/Horus_Web/frontend/node_modules/@unicef/material-ui-currency-textfield/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/unicef__material-ui-currency-textfield` if it exists or add a new declaration (.d.ts) file containing `declare module '@unicef/material-ui-currency-textfield'

Any tip?

Thank you

**Comment by joshualessadias** [comment]
how did you solve this issue?
