### ISSUE TITLE
wants to disable the onWheel event I am using this CurrencyTextField in Redux form

### ISSUE THREAD

**Issue by Dhirajbhujbal** [unicef/material-ui-currency-textfield#16]
wants to disable the onWheel event I am using this CurrencyTextField in Redux form

CurrencyTextField
          className='form-control'
          // autoFocus={false}
          currencySymbol="₹"
          value={value}
          textAlign="left"
          minimumValue={0}
          onChange={(event, value) => {
            this.props.change('*****', value);
          }} />

**Comment by merlos** [comment]
'****' is not a valid number
