### ISSUE TITLE
Problem with error indicator

### ISSUE THREAD

**Issue by cyberixae** [unicef/material-ui-currency-textfield#3]
I'm encountering a problem with setting error state to indicate a problematic value. Everything seems to work fine if I just set `error={true}` but if I set error to true based on some state the currency field ends up copying the currency indicator in to the value. The field ends up reading `EUR       EUR10.00` and editing the value doesn't work correctly because `EUR` is included as part of the value of the native input element.

**Comment by cyberixae** [comment]
I'm experiencing a similar problem with a helperText that depends on the input value. Perhaps the component has some more fundamental problem related to properties that depend on the value of the field.

**Comment by sureshsevarthi** [comment]
Hey @cyberixae 
Sorry for the issue and thanks for letting us know. i'm working on it, i will resolve it as soon as possible.

**Comment by cyberixae** [comment]
@sureshsevarthi no need to apologize but it is of course nice if we can figure out what the problem really is. Let me know whether or not you can reproduce the problem. I can try to create an isolated code example if you'd find that helpful.

**Comment by sureshsevarthi** [comment]
Fixed an issue with new version @unicef/material-ui: "0.8.4".
Updating to it will solve the issue.
Added an example in [documentation ](https://unicef.github.io/material-ui-currency-textfield/)
look for "error and helperText", it may be useful.
