### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by rohmanhm** [unicef/material-ui-currency-textfield#6]

**Comment by merlos** [comment]
Initially it is not in our roadmap as we don´t use Typescript, but we welcome PR :)

**Comment by sureshsevarthi** [comment]
Hey @rohmanhm, we are going add typescript soon.

**Comment by merlos** [comment]
Added to latest release 0.8.6 https://www.npmjs.com/package/@unicef/material-ui-currency-textfield

**Comment by giorgiofellipe** [comment]
@merlos actually it isn't working yet. As I can see type definition files were removed from the PR #14 before merging.

**Comment by mirind4** [comment]
Why is this issue closed? It is not working yet as @giorgiofellipe also refers to it...
Can we open it again? thanks!

**Comment by keemor** [comment]
Hi @sureshsevarthi and @merlos,

Could you give some heads up do you plan to add TS support?

Cheers,

**Comment by cesarlarsson** [comment]
Any news?

**Comment by sureshsevarthi** [comment]
Hey @cesarlarsson @keemor @mirind4, @giorgiofellipe 

 We welcome PR's from you guys or else I will add it few weeks.

**Comment by devSarry** [comment]
Still no TS support. I see there's an open PR #46 . Could one of the maintainers please take a look.
