### ISSUE TITLE
Max input length

### ISSUE THREAD

**Issue by fogrock** [unicef/material-ui-currency-textfield#9]
Component' input appears to have max value of 9,999,999,999,999.99 - can it be greater that this?

**Comment by merlos** [comment]
Did you already tried changing the prop `maximumValue`?

**Comment by sureshsevarthi** [comment]
Hey @fogrock,
In autonumeric default value for maximumValue is  10000000000000. It can increased or decreased based on your need.
I updated the documentation with example on maximumValue and minimumValue, And also updated the defaultProps. [https://unicef.github.io/material-ui-currency-textfield/](url)

Solution:
try setting up the maximumValue as prop
Ex: maximumValue={100000000000000000}
